def main():
      print("【今日のnote投稿提案書】")
      print("")
      print("■ 今日のテーマ")
      print("AIで人生を変えていく過程")
      print("")
      print("■ タイトル案")
      print("① 保険営業マンがAIを使い始めたら、毎朝が変わった話")
      print("② 難しそうと思っていたAIを使ってみた正直な感想")
      print("③ Claude Codeを触って3日目の初心者が感じたこと")
      print("")
      print("■ おすすめタイトル")
      print("保険営業マンがAIを使い始めたら、毎朝が変わった話")
      print("")
      print("■ 書き出し")
      print("正直、最初はAIなんて自分には関係ないと思っていた。")
      print("")
      print("■ 見出し")
      print("1. きっかけは時間がもったいないという一言")
      print("2. 実際にやってみてわかった3つのこと")
      print("3. 失敗しても続けられた理由")
      print("")
      print("■ SNS短文")
      print("保険営業マンがAI使い始めました。不器用でもやってみる話を書きます。")
      print("")
      print("■ 今日の狙い")
      print("AIに興味はあるけど踏み出せていない人に自分もできるかもと思ってもらう")

  if __name__ == "__main__":
      main()
